language: node_js
node_js:
  - node
script:
  - yarn verify
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: dist/*.js
    api_key: $GH_TOKEN
    on:
      tags: true